name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      XCODE_PROJECT: MyFinance.xcodeproj
      XCODE_SCHEME: MyFinance

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

# xcodebuild clean build test \
#   -project MyFinance.xcodeproj \
#   -scheme MyFinance \
#   -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
#   -enableCodeCoverage YES | xcpretty

    - name: Build and test for iOS
      run: |
        xcodebuild clean build test \
          -project MyFinance.xcodeproj \
          -scheme MyFinance \
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
          -enableCodeCoverage YES | xcpretty
